import { useLocalStorage } from './useLocalStorage';
import type {
  WeeklyUpdate, PodUpdateSummary, MeetingNote, JournalEntry,
  Pod, AppSettings, GitHubSnapshot, NoteTag,
} from '../types';
import { RISK_META } from '../types';
import { format } from 'date-fns';

function generateId() {
  return `update-${Date.now()}`;
}

function getMondayOfCurrentWeek(): string {
  const now = new Date();
  const day = now.getDay();
  const diff = day === 0 ? 6 : day - 1;
  const monday = new Date(now);
  monday.setDate(now.getDate() - diff);
  monday.setHours(0, 0, 0, 0);
  return monday.toISOString();
}

function groupEntriesByTag(
  notes: MeetingNote[],
  journals: JournalEntry[],
): Record<NoteTag, string[]> {
  const result: Record<NoteTag, string[]> = {
    risk: [], highlight: [], callout: [], blocker: [], note: [],
  };

  for (const note of notes) {
    for (const entry of note.entries) {
      if (entry.includeInUpdate) {
        result[entry.tag].push(entry.text);
      }
    }
  }
  for (const journal of journals) {
    for (const entry of journal.entries) {
      if (entry.includeInUpdate) {
        result[entry.tag].push(entry.text);
      }
    }
  }

  return result;
}

function riskEmoji(level: string): string {
  const map: Record<string, string> = {
    low: '🟢', medium: '🟡', high: '🟠', critical: '🔴',
  };
  return map[level] ?? '⚪';
}

function formatUpdateBody(
  summaries: PodUpdateSummary[],
  settings: AppSettings,
  weekOf: string,
): string {
  const weekStr = format(new Date(weekOf), 'MMMM d, yyyy');
  const critical = summaries.filter(s => s.riskLevel === 'critical');
  const high = summaries.filter(s => s.riskLevel === 'high');

  let body = `# AI Platform Weekly Update — Week of ${weekStr}\n\n`;
  body += `**Prepared by:** ${settings.pmName}  \n`;
  body += `**Recipients:** ${settings.leadershipNames}\n\n`;
  body += `---\n\n`;

  // Executive summary
  const atRisk = [...critical, ...high];
  if (atRisk.length > 0) {
    body += `## Executive Summary\n\n`;
    body += `Portfolio has **${critical.length} critical** and **${high.length} high-risk** pods this week. `;
    if (critical.length > 0) {
      body += `Immediate attention needed on: ${critical.map(s => s.podName).join(', ')}. `;
    }
    const green = summaries.filter(s => s.riskLevel === 'low' || s.riskLevel === 'medium');
    body += `${green.length} pods are tracking well.\n\n`;
  } else {
    body += `## Executive Summary\n\nAll pods are tracking at medium risk or below this week. Strong delivery momentum across the portfolio.\n\n`;
  }

  // Risk table
  body += `## Risk Overview\n\n`;
  body += `| Pod | Risk | Blockers | Key Issue |\n`;
  body += `|-----|------|----------|-----------|\n`;
  for (const s of summaries) {
    const topIssue = s.blockers[0] ?? s.risks[0] ?? s.callouts[0] ?? '—';
    const shortIssue = topIssue.length > 60 ? topIssue.slice(0, 57) + '...' : topIssue;
    body += `| ${riskEmoji(s.riskLevel)} ${s.podName} | ${RISK_META[s.riskLevel].label} | ${s.blockers.length} | ${shortIssue} |\n`;
  }
  body += `\n---\n\n`;

  // Per-pod updates
  body += `## Pod Updates\n\n`;
  for (const s of summaries) {
    body += `### ${s.podName}\n`;
    body += `**Risk:** ${riskEmoji(s.riskLevel)} ${RISK_META[s.riskLevel].label}\n\n`;

    if (s.highlights.length > 0) {
      body += `**⭐ Highlights**\n`;
      s.highlights.forEach(h => body += `- ${h}\n`);
      body += `\n`;
    }
    if (s.blockers.length > 0) {
      body += `**🚫 Blockers**\n`;
      s.blockers.forEach(b => body += `- ${b}\n`);
      body += `\n`;
    }
    if (s.risks.length > 0) {
      body += `**🚨 Risks**\n`;
      s.risks.forEach(r => body += `- ${r}\n`);
      body += `\n`;
    }
    if (s.callouts.length > 0) {
      body += `**📢 Callouts**\n`;
      s.callouts.forEach(c => body += `- ${c}\n`);
      body += `\n`;
    }
    if (s.generalNotes.length > 0) {
      body += `**📝 Notes**\n`;
      s.generalNotes.forEach(n => body += `- ${n}\n`);
      body += `\n`;
    }

    body += `---\n\n`;
  }

  body += `*Generated by Meeting Planner · ${format(new Date(), 'PPpp')}*\n`;
  return body;
}

export function useUpdates(
  pods: Pod[],
  notes: MeetingNote[],
  journals: JournalEntry[],
  settings: AppSettings,
  githubCache: Record<string, GitHubSnapshot>,
) {
  const [updates, setUpdates] = useLocalStorage<WeeklyUpdate[]>('mp:updates', []);

  function generateUpdate(): WeeklyUpdate {
    const weekOf = getMondayOfCurrentWeek();
    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);

    const recentNotes = notes.filter(n => new Date(n.createdAt) >= weekAgo);
    const recentJournals = journals.filter(j => new Date(j.createdAt) >= weekAgo);

    const podSummaries: PodUpdateSummary[] = pods.map(pod => {
      const podNotes = recentNotes.filter(n => n.podId === pod.id);
      const podJournals = recentJournals.filter(j => j.podId === pod.id);
      const grouped = groupEntriesByTag(podNotes, podJournals);

      return {
        podId: pod.id,
        podName: pod.name,
        riskLevel: pod.riskLevel,
        highlights: grouped.highlight,
        blockers: grouped.blocker,
        callouts: grouped.callout,
        risks: grouped.risk,
        generalNotes: grouped.note,
        githubSnapshot: githubCache[pod.id] ?? null,
      };
    });

    // Sort: critical → high → medium → low
    const riskOrder = { critical: 0, high: 1, medium: 2, low: 3 };
    podSummaries.sort((a, b) => riskOrder[a.riskLevel] - riskOrder[b.riskLevel]);

    const body = formatUpdateBody(podSummaries, settings, weekOf);
    const weekStr = format(new Date(weekOf), 'MMM d');

    const update: WeeklyUpdate = {
      id: generateId(),
      weekOf,
      generatedAt: new Date().toISOString(),
      sentAt: null,
      recipientList: settings.updateRecipients,
      subject: `AI Platform Weekly Update — Week of ${weekStr}`,
      body,
      podSummaries,
      editedBeforeSend: false,
    };

    setUpdates(prev => {
      // Replace any existing draft for this week
      const filtered = prev.filter(u => u.weekOf !== weekOf || u.sentAt !== null);
      return [update, ...filtered];
    });

    return update;
  }

  function saveUpdate(update: WeeklyUpdate) {
    setUpdates(prev => prev.map(u => u.id === update.id ? update : u));
  }

  function markSent(id: string) {
    setUpdates(prev => prev.map(u =>
      u.id === id ? { ...u, sentAt: new Date().toISOString() } : u
    ));
  }

  function deleteUpdate(id: string) {
    setUpdates(prev => prev.filter(u => u.id !== id));
  }

  const currentWeekOf = getMondayOfCurrentWeek();
  const currentDraft = updates.find(u => u.weekOf === currentWeekOf && u.sentAt === null) ?? null;

  return { updates, currentDraft, generateUpdate, saveUpdate, markSent, deleteUpdate };
}
